quarkus:
  rest-client:
    feedback-app-api:
      url: http://localhost:8081
      headers:
        Authorization: Basic YWRtaW5AZW1haWwuY29tOmFkbWlu
  mailer:
    from: "no-reply@yourdomain.com"
    host: "smtp.gmail.com"
    port: 587
    username: "your_email@gmail.com"
    password: "your_password"
    start-tls: OPTIONAL
