quarkus:
  rest-client:
    feedback-app-api:
      url: http://feedback-app:8080
  mailer:
    from: "no-reply@yourdomain.com"
    host: "smtp.gmail.com"
    port: 587
    username: "your_email@gmail.com"
    password: "your_password"
    start-tls: OPTIONAL
